<?php

use DeveloperHub\HidePrice\Block\Customer;
use Magento\Catalog\Block\Product\ListProduct;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\ActionInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

?>
<?php
/**
 * Product list template
 *
 * @var $block ListProduct
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
$customBlock = $block->getLayout()->createBlock(Customer::class);
$data = $customBlock->getCustomer();
$authorizationBlock = $block->getLayout()->createBlock(Magento\Customer\Block\Account\AuthorizationLink::class);
$dataPostParam = '';
if ($authorizationBlock->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
$helper = $this->helper(\DeveloperHub\HidePrice\Helper\Data::class);
$configFieldEnable = $helper->getConfigFieldEnable();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info"
                         id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                         data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = 'left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;';
                        }
                        ?>
                        <?php // Product Image?>
                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                           class="product photo product-item-photo"
                           tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                    <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?php if ($configFieldEnable == 1):?>
                                <button id="hide-price" class= 'btn btn-secondary hide-price'
                                        data-order-name="<?php echo $_product->getName(); ?>"
                                        data-order-id = "<?php echo $_product->getId()?>"
                                        data-order-price = "<?php echo $_product->getData('price')?>"
                                        data-mage-init='{"example-modal": {"target": "#modal-content"}}'>
                                    <?php echo 'Call For Price'  ?>
                                </button>
                            <?php else:?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                            <?php endif;?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($_product->isSaleable()):?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                  method="post">
                                                <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                                <?php foreach ($options as $optionItem): ?>
                                                    <input type="hidden"
                                                           name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                           value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                                <?php endforeach; ?>
                                                <input type="hidden"
                                                       name="product"
                                                       value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                <input type="hidden"
                                                       name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED ?>"
                                                       value="<?=
                                                       /* @noEscape */ $postParams['data'][ActionInterface::PARAM_NAME_URL_ENCODED]
                                                       ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <?php if ($data):?>
                                                    <button type="submit"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary"
                                                            disabled>
                                                        <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                <?php else:?>
                                                    <button type="submit"
                                                            title="<?= $escaper->escapeHtmlAttr(__('sign in')) ?>"
                                                            class="link authorization-link">
                                                            <a <?= /* @noEscape */ $authorizationBlock->getLinkAttributes() ?>
                                                            <?= /* @noEscape */ $dataPostParam ?>><?= $escaper->escapeHtml($authorizationBlock->getLabel()) ?></a>
                                                    </button>
                                                <?php endif;?>
                                            </form>
                                        <?php else:?>
                                            <?php if ($_product->isAvailable()):?>
                                                <div class="stock available">
                                                    <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else:?>
                                                <div class="stock unavailable">
                                                    <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                        ) : '' ?>
                                    <div data-role="add-to-links" class="actions-secondary">
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                    <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                        ) : '' ?>
                                </div>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?= /* @noEscape */ $_helper->productAttribute(
                                            $_product,
                                            $_product->getShortDescription(),
                                            'short_description'
                                        ) ?>
                                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                           title="<?= /* @noEscape */ $_productNameStripped ?>"
                                           class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                            $position,
                            'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                        ) : '' ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }
    </script>
<?php endif; ?>
<div id="devhub-cancel-order-modal" style="display: none;">
    <form action="" class="form cancel-order" id="hide-price-form" method="post"
          data-hasrequired="<?= $escaper->escapeHtml(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <div class="control">
                <input type="hidden" name="id" value="" class="id">
                <input type="hidden" name="price" value="" class="price">
                <?php $formKey = $block->getFormKey()?>
                <input type="hidden" name="form_key" value="<?= $escaper->escapeHtml($formKey) ?>" class="form_key">
            </div>
            <div class="field required">
                <div class="control">
                    <input type="text" name="product-name" value="" class="product-name" disabled>
                    <label for="">Name</label>
                    <input type="text" name="name" class="input-name" id="input_name"/>
                    <label for="">Email</label>
                    <input type="text" name="email" class="input-email" id="input_email"/>
                    <label for="">Number</label>
                    <input type="text" name="number" class="input-num" id="input_num"/>
                    <label>
                        Request Details
                        <textarea class="devhub-cancel-order-reason input-text" name="comment" data-validate="{required:true}"></textarea>
                    </label>
                </div>
            </div>
        </fieldset>
    </form>
</div>
